# Generated by Django 3.0.6 on 2020-07-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_cards'),
        ('card', '0003_auto_20200701_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_info', to='user.Profile'),
        ),
    ]
