# Generated by Django 3.0.6 on 2020-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(default='null customer', max_length=100),
            preserve_default=False,
        ),
    ]
