# Generated by Django 3.0.6 on 2020-06-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_id',
        ),
    ]
