# Generated by Django 3.0.6 on 2020-06-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
