# Generated by Django 3.0.6 on 2020-07-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200628_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
