# Generated by Django 3.0.6 on 2020-07-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
